### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Saicharan67** [Saicharan67/Interview-Coding-Questions#14]
As of now, the readme file is not that good. A readme file is like a Summary page of a book. So, we have to update readme file so that it contains all the information about the repo

**Comment by kunalkumar007** [comment]
I am done with the #13 issue, I want to take this issue into account as well. 😄

**Comment by Saicharan67** [comment]
Great, first do some googling on what can be the template for the readme. Finalize some good templates and after that we can implement them.
